<?php

use App\City;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\support\str;

class CitySeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $row = 1;
    $raw_cities = array(
      'Abia' =>
      array(
        0 => 'Aba North',
        1 => 'Aba South',
        2 => 'Arochukwu',
        3 => 'Bende',
        4 => 'Ikawuno',
        5 => 'Ikwuano',
        6 => 'Isiala-Ngwa North',
        7 => 'Isiala-Ngwa South',
        8 => 'Isuikwuato',
        9 => 'Umu Nneochi',
        10 => 'Obi Ngwa',
        11 => 'Obioma Ngwa',
        12 => 'Ohafia',
        13 => 'Ohaozara',
        14 => 'Osisioma',
        15 => 'Ugwunagbo',
        16 => 'Ukwa West',
        17 => 'Ukwa East',
        18 => 'Umuahia North',
        19 => 'Umuahia South',
      ),
      'Adamawa' =>
      array(
        0 => 'Demsa',
        1 => 'Fufore',
        2 => 'Ganye',
        3 => 'Girei',
        4 => 'Gombi',
        5 => 'Guyuk',
        6 => 'Hong',
        7 => 'Jada',
        8 => 'Lamurde',
        9 => 'Madagali',
        10 => 'Maiha',
        11 => 'Mayo-Belwa',
        12 => 'Michika',
        13 => 'Mubi-North',
        14 => 'Mubi-South',
        15 => 'Numan',
        16 => 'Shelleng',
        17 => 'Song',
        18 => 'Toungo',
        19 => 'Yola North',
        20 => 'Yola South',
      ),
      'Akwa Ibom' =>
      array(
        0 => 'Abak',
        1 => 'Eastern-Obolo',
        2 => 'Eket',
        3 => 'Esit-Eket',
        4 => 'Essien-Udim',
        5 => 'Etim-Ekpo',
        6 => 'Etinan',
        7 => 'Ibeno',
        8 => 'Ibesikpo-Asutan',
        9 => 'Ibiono-Ibom',
        10 => 'Ika',
        11 => 'Ikono',
        12 => 'Ikot-Abasi',
        13 => 'Ikot-Ekpene',
        14 => 'Ini',
        15 => 'Itu',
        16 => 'Mbo',
        17 => 'Mkpat-Enin',
        18 => 'Nsit-Atai',
        19 => 'Nsit-Ibom',
        20 => 'Nsit-Ubium',
        21 => 'Obot-Akara',
        22 => 'Okobo',
        23 => 'Onna',
        24 => 'Oron',
        25 => 'Oruk Anam',
        26 => 'Udung-Uko',
        27 => 'Ukanafun',
        28 => 'Urue-Offong/Oruko',
        29 => 'Uruan',
        30 => 'Uyo',
      ),
      'Anambra' =>
      array(
        0 => 'Aguata',
        1 => 'Anambra East',
        2 => 'Anambra West',
        3 => 'Anaocha',
        4 => 'Awka North',
        5 => 'Awka South',
        6 => 'Ayamelum',
        7 => 'Dunukofia',
        8 => 'Ekwusigo',
        9 => 'Idemili-North',
        10 => 'Idemili-South',
        11 => 'Ihiala',
        12 => 'Njikoka',
        13 => 'Nnewi-North',
        14 => 'Nnewi-South',
        15 => 'Ogbaru',
        16 => 'Onitsha-North',
        17 => 'Onitsha-South',
        18 => 'Orumba-North',
        19 => 'Orumba-South',
      ),
      'Bauchi' =>
      array(
        0 => 'Alkaleri',
        1 => 'Bauchi',
        2 => 'Bogoro',
        3 => 'Damban',
        4 => 'Darazo',
        5 => 'Dass',
        6 => 'Gamawa',
        7 => 'Ganjuwa',
        8 => 'Giade',
        9 => 'Itas/Gadau',
        10 => 'Jama\'Are',
        11 => 'Katagum',
        12 => 'Kirfi',
        13 => 'Misau',
        14 => 'Ningi',
        15 => 'Shira',
        16 => 'Tafawa-Balewa',
        17 => 'Toro',
        18 => 'Warji',
        19 => 'Zaki',
      ),
      'Benue' =>
      array(
        0 => 'Ado',
        1 => 'Agatu',
        2 => 'Apa',
        3 => 'Buruku',
        4 => 'Gboko',
        5 => 'Guma',
        6 => 'Gwer-East',
        7 => 'Gwer-West',
        8 => 'Katsina-Ala',
        9 => 'Konshisha',
        10 => 'Kwande',
        11 => 'Logo',
        12 => 'Makurdi',
        13 => 'Ogbadibo',
        14 => 'Ohimini',
        15 => 'Oju',
        16 => 'Okpokwu',
        17 => 'Otukpo',
        18 => 'Tarka',
        19 => 'Ukum',
        20 => 'Ushongo',
        21 => 'Vandeikya',
      ),
      'Borno' =>
      array(
        0 => 'Abadam',
        1 => 'Askira-Uba',
        2 => 'Bama',
        3 => 'Bayo',
        4 => 'Biu',
        5 => 'Chibok',
        6 => 'Damboa',
        7 => 'Dikwa',
        8 => 'Gubio',
        9 => 'Guzamala',
        10 => 'Gwoza',
        11 => 'Hawul',
        12 => 'Jere',
        13 => 'Kaga',
        14 => 'Kala/Balge',
        15 => 'Konduga',
        16 => 'Kukawa',
        17 => 'Kwaya-Kusar',
        18 => 'Mafa',
        19 => 'Magumeri',
        20 => 'Maiduguri',
        21 => 'Marte',
        22 => 'Mobbar',
        23 => 'Monguno',
        24 => 'Ngala',
        25 => 'Nganzai',
        26 => 'Shani',
      ),
      'Bayelsa' =>
      array(
        0 => 'Brass',
        1 => 'Ekeremor',
        2 => 'Kolokuma/Opokuma',
        3 => 'Nembe',
        4 => 'Ogbia',
        5 => 'Sagbama',
        6 => 'Southern-Ijaw',
        7 => 'Yenagoa',
      ),
      'Cross River' =>
      array(
        0 => 'Abi',
        1 => 'Akamkpa',
        2 => 'Akpabuyo',
        3 => 'Bakassi',
        4 => 'Bekwarra',
        5 => 'Biase',
        6 => 'Boki',
        7 => 'Calabar-Municipal',
        8 => 'Calabar-South',
        9 => 'Etung',
        10 => 'Ikom',
        11 => 'Obanliku',
        12 => 'Obubra',
        13 => 'Obudu',
        14 => 'Odukpani',
        15 => 'Ogoja',
        16 => 'Yakurr',
        17 => 'Yala',
      ),
      'Delta' =>
      array(
        0 => 'Aniocha North',
        1 => 'Aniocha-North',
        2 => 'Aniocha-South',
        3 => 'Bomadi',
        4 => 'Burutu',
        5 => 'Ethiope-East',
        6 => 'Ethiope-West',
        7 => 'Ika-North-East',
        8 => 'Ika-South',
        9 => 'Isoko-North',
        10 => 'Isoko-South',
        11 => 'Ndokwa-East',
        12 => 'Ndokwa-West',
        13 => 'Okpe',
        14 => 'Oshimili-North',
        15 => 'Oshimili-South',
        16 => 'Patani',
        17 => 'Sapele',
        18 => 'Udu',
        19 => 'Ughelli-North',
        20 => 'Ughelli-South',
        21 => 'Ukwuani',
        22 => 'Uvwie',
        23 => 'Warri South-West',
        24 => 'Warri North',
        25 => 'Warri South',
      ),
      'Ebonyi' =>
      array(
        0 => 'Abakaliki',
        1 => 'Afikpo-North',
        2 => 'Afikpo South (Edda)',
        3 => 'Ebonyi',
        4 => 'Ezza-North',
        5 => 'Ezza-South',
        6 => 'Ikwo',
        7 => 'Ishielu',
        8 => 'Ivo',
        9 => 'Izzi',
        10 => 'Ohaukwu',
        11 => 'Onicha',
      ),
      'Edo' =>
      array(
        0 => 'Akoko Edo',
        1 => 'Egor',
        2 => 'Esan-Central',
        3 => 'Esan-North-East',
        4 => 'Esan-South-East',
        5 => 'Esan-West',
        6 => 'Etsako-Central',
        7 => 'Etsako-East',
        8 => 'Etsako-West',
        9 => 'Igueben',
        10 => 'Ikpoba-Okha',
        11 => 'Oredo',
        12 => 'Orhionmwon',
        13 => 'Ovia-North-East',
        14 => 'Ovia-South-West',
        15 => 'Owan East',
        16 => 'Owan-West',
        17 => 'Uhunmwonde',
      ),
      'Ekiti' =>
      array(
        0 => 'Ado-Ekiti',
        1 => 'Efon',
        2 => 'Ekiti-East',
        3 => 'Ekiti-South-West',
        4 => 'Ekiti-West',
        5 => 'Emure',
        6 => 'Gbonyin',
        7 => 'Ido-Osi',
        8 => 'Ijero',
        9 => 'Ikere',
        10 => 'Ikole',
        11 => 'Ilejemeje',
        12 => 'Irepodun/Ifelodun',
        13 => 'Ise-Orun',
        14 => 'Moba',
        15 => 'Oye',
      ),
      'Enugu' =>
      array(
        0 => 'Aninri',
        1 => 'Awgu',
        2 => 'Enugu-East',
        3 => 'Enugu-North',
        4 => 'Enugu-South',
        5 => 'Ezeagu',
        6 => 'Igbo-Etiti',
        7 => 'Igbo-Eze-North',
        8 => 'Igbo-Eze-South',
        9 => 'Isi-Uzo',
        10 => 'Nkanu-East',
        11 => 'Nkanu-West',
        12 => 'Nsukka',
        13 => 'Oji-River',
        14 => 'Udenu',
        15 => 'Udi',
        16 => 'Uzo-Uwani',
      ),
      'Abuja' =>
      array(
        0 => 'Abuja',
        1 => 'Kwali',
        2 => 'Kuje',
        3 => 'Gwagwalada',
        4 => 'Bwari',
        5 => 'Abaji',
      ),
      'Gombe' =>
      array(
        0 => 'Akko',
        1 => 'Balanga',
        2 => 'Billiri',
        3 => 'Dukku',
        4 => 'Funakaye',
        5 => 'Gombe',
        6 => 'Kaltungo',
        7 => 'Kwami',
        8 => 'Nafada',
        9 => 'Shongom',
        10 => 'Yamaltu/Deba',
      ),
      'Imo' =>
      array(
        0 => 'Aboh-Mbaise',
        1 => 'Ahiazu-Mbaise',
        2 => 'Ehime-Mbano',
        3 => 'Ezinihitte',
        4 => 'Ideato-North',
        5 => 'Ideato-South',
        6 => 'Ihitte/Uboma',
        7 => 'Ikeduru',
        8 => 'Isiala-Mbano',
        9 => 'Isu',
        10 => 'Mbaitoli',
        11 => 'Ngor-Okpala',
        12 => 'Njaba',
        13 => 'Nkwerre',
        14 => 'Nwangele',
        15 => 'Obowo',
        16 => 'Oguta',
        17 => 'Ohaji-Egbema',
        18 => 'Okigwe',
        19 => 'Onuimo',
        20 => 'Orlu',
        21 => 'Orsu',
        22 => 'Oru-East',
        23 => 'Oru-West',
        24 => 'Owerri-Municipal',
        25 => 'Owerri-North',
        26 => 'Owerri-West',
      ),
      'Jigawa' =>
      array(
        0 => 'Auyo',
        1 => 'Babura',
        2 => 'Biriniwa',
        3 => 'Birnin-Kudu',
        4 => 'Buji',
        5 => 'Dutse',
        6 => 'Gagarawa',
        7 => 'Garki',
        8 => 'Gumel',
        9 => 'Guri',
        10 => 'Gwaram',
        11 => 'Gwiwa',
        12 => 'Hadejia',
        13 => 'Jahun',
        14 => 'Kafin-Hausa',
        15 => 'Kaugama',
        16 => 'Kazaure',
        17 => 'Kiri kasama',
        18 => 'Maigatari',
        19 => 'Malam Madori',
        20 => 'Miga',
        21 => 'Ringim',
        22 => 'Roni',
        23 => 'Sule-Tankarkar',
        24 => 'Taura',
        25 => 'Yankwashi',
      ),
      'Kebbi' =>
      array(
        0 => 'Aleiro',
        1 => 'Arewa-Dandi',
        2 => 'Argungu',
        3 => 'Augie',
        4 => 'Bagudo',
        5 => 'Birnin-Kebbi',
        6 => 'Bunza',
        7 => 'Dandi',
        8 => 'Fakai',
        9 => 'Gwandu',
        10 => 'Jega',
        11 => 'Kalgo',
        12 => 'Koko-Besse',
        13 => 'Maiyama',
        14 => 'Ngaski',
        15 => 'Sakaba',
        16 => 'Shanga',
        17 => 'Suru',
        18 => 'Wasagu/Danko',
        19 => 'Yauri',
        20 => 'Zuru',
      ),
      'Kaduna' =>
      array(
        0 => 'Birnin-Gwari',
        1 => 'Chikun',
        2 => 'Giwa',
        3 => 'Igabi',
        4 => 'Ikara',
        5 => 'Jaba',
        6 => 'Jema\'A',
        7 => 'Kachia',
        8 => 'Kaduna-North',
        9 => 'Kaduna-South',
        10 => 'Kagarko',
        11 => 'Kajuru',
        12 => 'Kaura',
        13 => 'Kauru',
        14 => 'Kubau',
        15 => 'Kudan',
        16 => 'Lere',
        17 => 'Makarfi',
        18 => 'Sabon-Gari',
        19 => 'Sanga',
        20 => 'Soba',
        21 => 'Zangon-Kataf',
        22 => 'Zaria',
      ),
      'Kano' =>
      array(
        0 => 'Ajingi',
        1 => 'Albasu',
        2 => 'Bagwai',
        3 => 'Bebeji',
        4 => 'Bichi',
        5 => 'Bunkure',
        6 => 'Dala',
        7 => 'Dambatta',
        8 => 'Dawakin-Kudu',
        9 => 'Dawakin-Tofa',
        10 => 'Doguwa',
        11 => 'Fagge',
        12 => 'Gabasawa',
        13 => 'Garko',
        14 => 'Garun-Mallam',
        15 => 'Gaya',
        16 => 'Gezawa',
        17 => 'Gwale',
        18 => 'Gwarzo',
        19 => 'Kabo',
        20 => 'Kano-Municipal',
        21 => 'Karaye',
        22 => 'Kibiya',
        23 => 'Kiru',
        24 => 'Kumbotso',
        25 => 'Kunchi',
        26 => 'Kura',
        27 => 'Madobi',
        28 => 'Makoda',
        29 => 'Minjibir',
        30 => 'Nasarawa',
        31 => 'Rano',
        32 => 'Rimin-Gado',
        33 => 'Rogo',
        34 => 'Shanono',
        35 => 'Sumaila',
        36 => 'Takai',
        37 => 'Tarauni',
        38 => 'Tofa',
        39 => 'Tsanyawa',
        40 => 'Tudun-Wada',
        41 => 'Ungogo',
        42 => 'Warawa',
        43 => 'Wudil',
      ),
      'Kogi' =>
      array(
        0 => 'Adavi',
        1 => 'Ajaokuta',
        2 => 'Ankpa',
        3 => 'Dekina',
        4 => 'Ibaji',
        5 => 'Idah',
        6 => 'Igalamela-Odolu',
        7 => 'Ijumu',
        8 => 'Kabba/Bunu',
        9 => 'Kogi',
        10 => 'Lokoja',
        11 => 'Mopa-Muro',
        12 => 'Ofu',
        13 => 'Ogori/Magongo',
        14 => 'Okehi',
        15 => 'Okene',
        16 => 'Olamaboro',
        17 => 'Omala',
        18 => 'Oyi',
        19 => 'Yagba-East',
        20 => 'Yagba-West',
      ),
      'Katsina' =>
      array(
        0 => 'Bakori',
        1 => 'Batagarawa',
        2 => 'Batsari',
        3 => 'Baure',
        4 => 'Bindawa',
        5 => 'Charanchi',
        6 => 'Dan-Musa',
        7 => 'Dandume',
        8 => 'Danja',
        9 => 'Daura',
        10 => 'Dutsi',
        11 => 'Dutsin-Ma',
        12 => 'Faskari',
        13 => 'Funtua',
        14 => 'Ingawa',
        15 => 'Jibia',
        16 => 'Kafur',
        17 => 'Kaita',
        18 => 'Kankara',
        19 => 'Kankia',
        20 => 'Katsina',
        21 => 'Kurfi',
        22 => 'Kusada',
        23 => 'Mai-Adua',
        24 => 'Malumfashi',
        25 => 'Mani',
        26 => 'Mashi',
        27 => 'Matazu',
        28 => 'Musawa',
        29 => 'Rimi',
        30 => 'Sabuwa',
        31 => 'Safana',
        32 => 'Sandamu',
        33 => 'Zango',
      ),
      'Kwara' =>
      array(
        0 => 'Asa',
        1 => 'Baruten',
        2 => 'Edu',
        3 => 'Ekiti (Araromi/Opin)',
        4 => 'Ilorin-East',
        5 => 'Ilorin-South',
        6 => 'Ilorin-West',
        7 => 'Isin',
        8 => 'Kaiama',
        9 => 'Moro',
        10 => 'Offa',
        11 => 'Oke-Ero',
        12 => 'Oyun',
        13 => 'Pategi',
      ),
      'Lagos' =>
      array(
        0 => 'Agege',
        1 => 'Ajeromi-Ifelodun',
        2 => 'Alimosho',
        3 => 'Amuwo-Odofin',
        4 => 'Apapa',
        5 => 'Badagry',
        6 => 'Epe',
        7 => 'Eti-Osa',
        8 => 'Ibeju-Lekki',
        9 => 'Ifako-Ijaiye',
        10 => 'Ikeja',
        11 => 'Ikorodu',
        12 => 'Kosofe',
        13 => 'Lagos-Island',
        14 => 'Lagos-Mainland',
        15 => 'Mushin',
        16 => 'Ojo',
        17 => 'Oshodi-Isolo',
        18 => 'Shomolu',
        19 => 'Surulere',
        20 => 'Yewa-South',
      ),
      'Nasarawa' =>
      array(
        0 => 'Akwanga',
        1 => 'Awe',
        2 => 'Doma',
        3 => 'Karu',
        4 => 'Keana',
        5 => 'Keffi',
        6 => 'Kokona',
        7 => 'Lafia',
        8 => 'Nasarawa',
        9 => 'Nasarawa-Eggon',
        10 => 'Obi',
        11 => 'Wamba',
        12 => 'Toto',
      ),
      'Niger' =>
      array(
        0 => 'Agaie',
        1 => 'Agwara',
        2 => 'Bida',
        3 => 'Borgu',
        4 => 'Bosso',
        5 => 'Chanchaga',
        6 => 'Edati',
        7 => 'Gbako',
        8 => 'Gurara',
        9 => 'Katcha',
        10 => 'Kontagora',
        11 => 'Lapai',
        12 => 'Lavun',
        13 => 'Magama',
        14 => 'Mariga',
        15 => 'Mashegu',
        16 => 'Mokwa',
        17 => 'Moya',
        18 => 'Paikoro',
        19 => 'Rafi',
        20 => 'Rijau',
        21 => 'Shiroro',
        22 => 'Suleja',
        23 => 'Tafa',
        24 => 'Wushishi',
      ),
      'Ogun' =>
      array(
        0 => 'Abeokuta-North',
        1 => 'Abeokuta-South',
        2 => 'Ado-Odo/Ota',
        3 => 'Ewekoro',
        4 => 'Ifo',
        5 => 'Ijebu-East',
        6 => 'Ijebu-North',
        7 => 'Ijebu-North-East',
        8 => 'Ijebu-Ode',
        9 => 'Ikenne',
        10 => 'Imeko-Afon',
        11 => 'Ipokia',
        12 => 'Obafemi-Owode',
        13 => 'Odeda',
        14 => 'Odogbolu',
        15 => 'Ogun-Waterside',
        16 => 'Remo-North',
        17 => 'Shagamu',
        18 => 'Yewa North',
      ),
      'Ondo' =>
      array(
        0 => 'Akoko North-East',
        1 => 'Akoko North-West',
        2 => 'Akoko South-West',
        3 => 'Akoko South-East',
        4 => 'Akure-North',
        5 => 'Akure-South',
        6 => 'Ese-Odo',
        7 => 'Idanre',
        8 => 'Ifedore',
        9 => 'Ilaje',
        10 => 'Ile-Oluji-Okeigbo',
        11 => 'Irele',
        12 => 'Odigbo',
        13 => 'Okitipupa',
        14 => 'Ondo West',
        15 => 'Ondo-East',
        16 => 'Ose',
        17 => 'Owo',
      ),
      'Osun' =>
      array(
        0 => 'Atakumosa West',
        1 => 'Atakumosa East',
        2 => 'Ayedaade',
        3 => 'Ayedire',
        4 => 'Boluwaduro',
        5 => 'Boripe',
        6 => 'Ede South',
        7 => 'Ede North',
        8 => 'Egbedore',
        9 => 'Ejigbo',
        10 => 'Ife North',
        11 => 'Ife South',
        12 => 'Ife-Central',
        13 => 'Ife-East',
        14 => 'Ifelodun',
        15 => 'Ila',
        16 => 'Ilesa-East',
        17 => 'Ilesa-West',
        18 => 'Irepodun',
        19 => 'Irewole',
        20 => 'Isokan',
        21 => 'Iwo',
        22 => 'Obokun',
        23 => 'Odo-Otin',
        24 => 'Ola Oluwa',
        25 => 'Olorunda',
        26 => 'Oriade',
        27 => 'Orolu',
        28 => 'Osogbo',
      ),
      'Oyo' =>
      array(
        0 => 'Afijio',
        1 => 'Akinyele',
        2 => 'Atiba',
        3 => 'Atisbo',
        4 => 'Egbeda',
        5 => 'Ibadan North',
        6 => 'Ibadan North-East',
        7 => 'Ibadan North-West',
        8 => 'Ibadan South-East',
        9 => 'Ibadan South-West',
        10 => 'Ibarapa-Central',
        11 => 'Ibarapa-East',
        12 => 'Ibarapa-North',
        13 => 'Ido',
        14 => 'Ifedayo',
        15 => 'Irepo',
        16 => 'Iseyin',
        17 => 'Itesiwaju',
        18 => 'Iwajowa',
        19 => 'Kajola',
        20 => 'Lagelu',
        21 => 'Ogo-Oluwa',
        22 => 'Ogbomosho-North',
        23 => 'Ogbomosho-South',
        24 => 'Olorunsogo',
        25 => 'Oluyole',
        26 => 'Ona-Ara',
        27 => 'Orelope',
        28 => 'Ori-Ire',
        29 => 'Oyo-West',
        30 => 'Oyo-East',
        31 => 'Saki-East',
        32 => 'Saki-West',
        33 => 'Surulere',
      ),
      'Plateau' =>
      array(
        0 => 'Barkin-Ladi',
        1 => 'Bassa',
        2 => 'Bokkos',
        3 => 'Jos-East',
        4 => 'Jos-North',
        5 => 'Jos-South',
        6 => 'Kanam',
        7 => 'Kanke',
        8 => 'Langtang-North',
        9 => 'Langtang-South',
        10 => 'Mangu',
        11 => 'Mikang',
        12 => 'Pankshin',
        13 => 'Qua\'an Pan',
        14 => 'Riyom',
        15 => 'Shendam',
        16 => 'Wase',
      ),
      'Rivers' =>
      array(
        0 => 'Abua/Odual',
        1 => 'Ahoada-East',
        2 => 'Ahoada-West',
        3 => 'Akuku Toru',
        4 => 'Andoni',
        5 => 'Asari-Toru',
        6 => 'Bonny',
        7 => 'Degema',
        8 => 'Eleme',
        9 => 'Emuoha',
        10 => 'Etche',
        11 => 'Gokana',
        12 => 'Ikwerre',
        13 => 'Khana',
        14 => 'Obio/Akpor',
        15 => 'Ogba-Egbema-Ndoni',
        16 => 'Ogba/Egbema/Ndoni',
        17 => 'Ogu/Bolo',
        18 => 'Okrika',
        19 => 'Omuma',
        20 => 'Opobo/Nkoro',
        21 => 'Oyigbo',
        22 => 'Port-Harcourt',
        23 => 'Tai',
      ),
      'Sokoto' =>
      array(
        0 => 'Binji',
        1 => 'Bodinga',
        2 => 'Dange-Shuni',
        3 => 'Gada',
        4 => 'Goronyo',
        5 => 'Gudu',
        6 => 'Gwadabawa',
        7 => 'Illela',
        8 => 'Kebbe',
        9 => 'Kware',
        10 => 'Rabah',
        11 => 'Sabon Birni',
        12 => 'Shagari',
        13 => 'Silame',
        14 => 'Sokoto-North',
        15 => 'Sokoto-South',
        16 => 'Tambuwal',
        17 => 'Tangaza',
        18 => 'Tureta',
        19 => 'Wamako',
        20 => 'Wurno',
        21 => 'Yabo',
      ),
      'Taraba' =>
      array(
        0 => 'Ardo-Kola',
        1 => 'Bali',
        2 => 'Donga',
        3 => 'Gashaka',
        4 => 'Gassol',
        5 => 'Ibi',
        6 => 'Jalingo',
        7 => 'Karim-Lamido',
        8 => 'Kurmi',
        9 => 'Lau',
        10 => 'Sardauna',
        11 => 'Takum',
        12 => 'Ussa',
        13 => 'Wukari',
        14 => 'Yorro',
        15 => 'Zing',
      ),
      'Yobe' =>
      array(
        0 => 'Bade',
        1 => 'Bursari',
        2 => 'Damaturu',
        3 => 'Fika',
        4 => 'Fune',
        5 => 'Geidam',
        6 => 'Gujba',
        7 => 'Gulani',
        8 => 'Jakusko',
        9 => 'Karasuwa',
        10 => 'Machina',
        11 => 'Nangere',
        12 => 'Nguru',
        13 => 'Potiskum',
        14 => 'Tarmuwa',
        15 => 'Yunusari',
        16 => 'Yusufari',
      ),
      'Zamfara' =>
      array(
        0 => 'Anka',
        1 => 'Bakura',
        2 => 'Birnin Magaji/Kiyaw',
        3 => 'Bukkuyum',
        4 => 'Bungudu',
        5 => 'Gummi',
        6 => 'Gusau',
        7 => 'Isa',
        8 => 'Kaura-Namoda',
        9 => 'Kiyawa',
        10 => 'Maradun',
        11 => 'Maru',
        12 => 'Shinkafi',
        13 => 'Talata-Mafara',
        14 => 'Tsafe',
        15 => 'Zurmi',
      ),
    );
    $raw_states = [
      'FC' => 'Abuja',
      'AB' => 'Abia',
      'AD' => 'Adamawa',
      'AK' => 'Akwa Ibom',
      'AN' => 'Anambra',
      'BA' => 'Bauchi',
      'BY' => 'Bayelsa',
      'BE' => 'Benue',
      'BO' => 'Borno',
      'CR' => 'Cross River',
      'DE' => 'Delta',
      'EB' => 'Ebonyi',
      'ED' => 'Edo',
      'EK' => 'Ekiti',
      'EN' => 'Enugu',
      'GO' => 'Gombe',
      'IM' => 'Imo',
      'JI' => 'Jigawa',
      'KD' => 'Kaduna',
      'KN' => 'Kano',
      'KT' => 'Katsina',
      'KE' => 'Kebbi',
      'KO' => 'Kogi',
      'KW' => 'Kwara',
      'LA' => 'Lagos',
      'NA' => 'Nasarawa',
      'NI' => 'Niger',
      'OG' => 'Ogun',
      'ON' => 'Ondo',
      'OS' => 'Osun',
      'OY' => 'Oyo',
      'PL' => 'Plateau',
      'RI' => 'Rivers',
      'SO' => 'Sokoto',
      'TA' => 'Taraba',
      'YO' => 'Yobe',
      'ZA' => 'Zamfara',
    ];
    $cities_data = [];

    foreach ($raw_states as $code => $data) {
      if ($raw_cities[$data] !== null) {
        foreach ($raw_cities[$data] as $value) {
          $cities_data[] = ['state_code' => $code, 'name' => $value];
        }
      }
    }

    $cities_count = count($cities_data);
    $cityProgressBar = $this->command->getOutput()->createProgressBar($cities_count);
    foreach ($cities_data as $city_data) {
      $city = [
        'name' => $city_data['name'],
        'state_code' => $city_data['state_code'],
        'slug' => Str::slug($city_data['name']),
      ];
      $cities[] = $city;
      City::create($city);
      $city = [];
      $cityProgressBar->advance();
    }
    $cityProgressBar->finish();
  }
}
