<?php

use App\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $currencies = array(
      array("country_iso" => "AD", "country_iso3" => "AND", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "AE", "country_iso3" => "ARE", "code" => "AED", "name" => "United Arab Emirates Dirham", "html_entity" => "&#1583;.&#1573;", "symbol" => "د.إ"),
      array("country_iso" => "AF", "country_iso3" => "AFG", "code" => "AFN", "name" => "Afghanistan Afghani", "html_entity" => "&#65;&#102;", "symbol" => "؋"),
      array("country_iso" => "AG", "country_iso3" => "ATG", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "AI", "country_iso3" => "AIA", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "AL", "country_iso3" => "ALB", "code" => "ALL", "name" => "Albania Lek", "html_entity" => "&#76;&#101;&#107;", "symbol" => "Lek"),
      array("country_iso" => "AM", "country_iso3" => "ARM", "code" => "AMD", "name" => "Armenia Dram", "html_entity" => "", "symbol" => NULL),
      array("country_iso" => "AN", "country_iso3" => "ANT", "code" => "ANG", "name" => "Netherlands Antilles Guilder", "html_entity" => "&#402;", "symbol" => "ƒ"),
      array("country_iso" => "AO", "country_iso3" => "AGO", "code" => "AOA", "name" => "Angola Kwanza", "html_entity" => "&#75;&#122;", "symbol" => "Kz"),
      array("country_iso" => "AQ", "country_iso3" => "ATA", "code" => NULL, "name" => NULL, "html_entity" => NULL, "symbol" => NULL),
      array("country_iso" => "AR", "country_iso3" => "ARG", "code" => "ARS", "name" => "Argentina Peso", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "AS", "country_iso3" => "ASM", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "AT", "country_iso3" => "AUT", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "AU", "country_iso3" => "AUS", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "AW", "country_iso3" => "ABW", "code" => "AWG", "name" => "Aruba Guilder", "html_entity" => "&#402;", "symbol" => "ƒ"),
      array("country_iso" => "AX", "country_iso3" => "ALA", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "AZ", "country_iso3" => "AZE", "code" => "AZN", "name" => "Azerbaijan New Manat", "html_entity" => "&#1084;&#1072;&#1085;", "symbol" => "ман"),
      array("country_iso" => "BA", "country_iso3" => "BIH", "code" => "BAM", "name" => "Bosnia and Herzegovina Convertible Marka", "html_entity" => "&#75;&#77;", "symbol" => "KM"),
      array("country_iso" => "BB", "country_iso3" => "BRB", "code" => "BBD", "name" => "Barbados Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "BD", "country_iso3" => "BGD", "code" => "BDT", "name" => "Bangladesh Taka", "html_entity" => "&#2547;", "symbol" => "৳"),
      array("country_iso" => "BE", "country_iso3" => "BEL", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "BF", "country_iso3" => "BFA", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "BG", "country_iso3" => "BGR", "code" => "BGN", "name" => "Bulgaria Lev", "html_entity" => "&#1083;&#1074;", "symbol" => "лв"),
      array("country_iso" => "BH", "country_iso3" => "BHR", "code" => "BHD", "name" => "Bahrain Dinar", "html_entity" => ".&#1583;.&#1576;", "symbol" => NULL),
      array("country_iso" => "BI", "country_iso3" => "BDI", "code" => "BIF", "name" => "Burundi Franc", "html_entity" => "&#70;&#66;&#117;", "symbol" => "FBu"),
      array("country_iso" => "BJ", "country_iso3" => "BEN", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "BL", "country_iso3" => "BLM", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "BM", "country_iso3" => "BMU", "code" => "BMD", "name" => "Bermuda Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "BN", "country_iso3" => "BRN", "code" => "BND", "name" => "Brunei Darussalam Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "BO", "country_iso3" => "BOL", "code" => "BOB", "name" => "Bolivia Boliviano", "html_entity" => "&#36;&#98;", "symbol" => '$b'),
      array("country_iso" => "BQ", "country_iso3" => "BES", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "BR", "country_iso3" => "BRA", "code" => "BRL", "name" => "Brazil Real", "html_entity" => "&#82;&#36;", "symbol" => "R$"),
      array("country_iso" => "BS", "country_iso3" => "BHS", "code" => "BSD", "name" => "Bahamas Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "BT", "country_iso3" => "BTN", "code" => "BTN", "name" => "Bhutan Ngultrum", "html_entity" => "&#78;&#117;&#46;", "symbol" => NULL),
      array("country_iso" => "BV", "country_iso3" => "BVT", "code" => "NOK", "name" => "Norway Krone", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "BW", "country_iso3" => "BWA", "code" => "BWP", "name" => "Botswana Pula", "html_entity" => "&#80;", "symbol" => "P"),
      array("country_iso" => "BY", "country_iso3" => "BLR", "code" => "BYR", "name" => "Belarus Ruble", "html_entity" => "&#112;&#46;", "symbol" => "p."),
      array("country_iso" => "BZ", "country_iso3" => "BLZ", "code" => "BZD", "name" => "Belize Dollar", "html_entity" => "&#66;&#90;&#36;", "symbol" => "BZ$"),
      array("country_iso" => "CA", "country_iso3" => "CAN", "code" => "CAD", "name" => "Canada Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "CC", "country_iso3" => "CCK", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "CD", "country_iso3" => "COD", "code" => "CDF", "name" => "Congo/Kinshasa Franc", "html_entity" => "&#70;&#67;", "symbol" => "Fr"),
      array("country_iso" => "CF", "country_iso3" => "CAF", "code" => "XAF", "name" => "Communauté Financière Africaine (BEAC) CFA Franc B", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "CG", "country_iso3" => "COG", "code" => "XAF", "name" => "Communauté Financière Africaine (BEAC) CFA Franc B", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "CH", "country_iso3" => "CHE", "code" => "CHF", "name" => "Switzerland Franc", "html_entity" => "", "symbol" => "Fr"),
      array("country_iso" => "CI", "country_iso3" => "CIV", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "CK", "country_iso3" => "COK", "code" => "NZD", "name" => "New Zealand Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "CL", "country_iso3" => "CHL", "code" => "CLP", "name" => "Chile Peso", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "CM", "country_iso3" => "CMR", "code" => "XAF", "name" => "Communauté Financière Africaine (BEAC) CFA Franc B", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "CN", "country_iso3" => "CHN", "code" => "CNY", "name" => "China Yuan Renminbi", "html_entity" => "&#165;", "symbol" => "¥"),
      array("country_iso" => "CO", "country_iso3" => "COL", "code" => "COP", "name" => "Colombia Peso", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "CR", "country_iso3" => "CRI", "code" => "CRC", "name" => "Costa Rica Colon", "html_entity" => "&#8353;", "symbol" => "₡"),
      array("country_iso" => "CS", "country_iso3" => "SCG", "code" => "RSD", "name" => "Serbia Dinar", "html_entity" => "&#1044;&#1080;&#1085;&#46;", "symbol" => "Дин."),
      array("country_iso" => "CU", "country_iso3" => "CUB", "code" => "CUP", "name" => "Cuba Peso", "html_entity" => "&#8396;", "symbol" => "₱"),
      array("country_iso" => "CV", "country_iso3" => "CPV", "code" => "CVE", "name" => "Cape Verde Escudo", "html_entity" => "&#x24;", "symbol" => "$"),
      array("country_iso" => "CW", "country_iso3" => "CUW", "code" => "ANG", "name" => "Netherlands Antilles Guilder", "html_entity" => "&#402;", "symbol" => "ƒ"),
      array("country_iso" => "CX", "country_iso3" => "CXR", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "CY", "country_iso3" => "CYP", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "CZ", "country_iso3" => "CZE", "code" => "CZK", "name" => "Czech Republic Koruna", "html_entity" => "&#75;&#269;", "symbol" => "Kč"),
      array("country_iso" => "DE", "country_iso3" => "DEU", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "DJ", "country_iso3" => "DJI", "code" => "DJF", "name" => "Djibouti Franc", "html_entity" => "&#70;&#100;&#106;", "symbol" => "Fr"),
      array("country_iso" => "DK", "country_iso3" => "DNK", "code" => "DKK", "name" => "Denmark Krone", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "DM", "country_iso3" => "DMA", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "DO", "country_iso3" => "DOM", "code" => "DOP", "name" => "Dominican Republic Peso", "html_entity" => "&#82;&#68;&#36;", "symbol" => "RD$"),
      array("country_iso" => "DZ", "country_iso3" => "DZA", "code" => "DZD", "name" => "Algeria Dinar", "html_entity" => "&#1583;&#1580;", "symbol" => "DA"),
      array("country_iso" => "EC", "country_iso3" => "ECU", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "EE", "country_iso3" => "EST", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "EG", "country_iso3" => "EGY", "code" => "EGP", "name" => "Egypt Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "EH", "country_iso3" => "ESH", "code" => "MAD", "name" => "Morocco Dirham", "html_entity" => "&#1583;.&#1605;.", "symbol" => "Dhs"),
      array("country_iso" => "ER", "country_iso3" => "ERI", "code" => "ERN", "name" => "Eritrea Nakfa", "html_entity" => "&#x4E;&#x66;&#x6B;", "symbol" => "Nfk"),
      array("country_iso" => "ES", "country_iso3" => "ESP", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "ET", "country_iso3" => "ETH", "code" => "ETB", "name" => "Ethiopia Birr", "html_entity" => "&#66;&#114;", "symbol" => "Br"),
      array("country_iso" => "FI", "country_iso3" => "FIN", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "FJ", "country_iso3" => "FJI", "code" => "FJD", "name" => "Fiji Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "FK", "country_iso3" => "FLK", "code" => "FKP", "name" => "Falkland Islands (Malvinas) Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "FM", "country_iso3" => "FSM", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "FO", "country_iso3" => "FRO", "code" => "DKK", "name" => "Denmark Krone", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "FR", "country_iso3" => "FRA", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "GA", "country_iso3" => "GAB", "code" => "XAF", "name" => "Communauté Financière Africaine (BEAC) CFA Franc B", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "GD", "country_iso3" => "GRD", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "GE", "country_iso3" => "GEO", "code" => "GEL", "name" => "Georgia Lari", "html_entity" => "&#4314;", "symbol" => NULL),
      array("country_iso" => "GF", "country_iso3" => "GUF", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "GG", "country_iso3" => "GGY", "code" => "GBP", "name" => "United Kingdom Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "GH", "country_iso3" => "GHA", "code" => "GHS", "name" => "Ghana Cedi", "html_entity" => "&#x47;&#x48;&#xA2;", "symbol" => "GH¢"),
      array("country_iso" => "GI", "country_iso3" => "GIB", "code" => "GIP", "name" => "Gibraltar Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "GL", "country_iso3" => "GRL", "code" => "DKK", "name" => "Denmark Krone", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "GM", "country_iso3" => "GMB", "code" => "GMD", "name" => "Gambia Dalasi", "html_entity" => "&#68;", "symbol" => "D"),
      array("country_iso" => "GN", "country_iso3" => "GIN", "code" => "GNF", "name" => "Guinea Franc", "html_entity" => "&#70;&#71;", "symbol" => "Fr"),
      array("country_iso" => "GP", "country_iso3" => "GLP", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "GQ", "country_iso3" => "GNQ", "code" => "XAF", "name" => "Communauté Financière Africaine (BEAC) CFA Franc B", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "GR", "country_iso3" => "GRC", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "GS", "country_iso3" => "SGS", "code" => "GBP", "name" => "United Kingdom Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "GT", "country_iso3" => "GTM", "code" => "GTQ", "name" => "Guatemala Quetzal", "html_entity" => "&#81;", "symbol" => "Q"),
      array("country_iso" => "GU", "country_iso3" => "GUM", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "GW", "country_iso3" => "GNB", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "GY", "country_iso3" => "GUY", "code" => "GYD", "name" => "Guyana Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "HK", "country_iso3" => "HKG", "code" => "HKD", "name" => "Hong Kong Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "HM", "country_iso3" => "HMD", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "HN", "country_iso3" => "HND", "code" => "HNL", "name" => "Honduras Lempira", "html_entity" => "&#76;", "symbol" => "L"),
      array("country_iso" => "HR", "country_iso3" => "HRV", "code" => "HRK", "name" => "Croatia Kuna", "html_entity" => "&#107;&#110;", "symbol" => "kn"),
      array("country_iso" => "HT", "country_iso3" => "HTI", "code" => "HTG", "name" => "Haiti Gourde", "html_entity" => "&#71;", "symbol" => NULL),
      array("country_iso" => "HU", "country_iso3" => "HUN", "code" => "HUF", "name" => "Hungary Forint", "html_entity" => "&#70;&#116;", "symbol" => "Ft"),
      array("country_iso" => "ID", "country_iso3" => "IDN", "code" => "IDR", "name" => "Indonesia Rupiah", "html_entity" => "&#82;&#112;", "symbol" => "Rp"),
      array("country_iso" => "IE", "country_iso3" => "IRL", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "IL", "country_iso3" => "ISR", "code" => "ILS", "name" => "Israel Shekel", "html_entity" => "&#8362;", "symbol" => "₪"),
      array("country_iso" => "IM", "country_iso3" => "IMN", "code" => "GBP", "name" => "United Kingdom Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "IN", "country_iso3" => "IND", "code" => "INR", "name" => "India Rupee", "html_entity" => "&#8377;", "symbol" => "₨"),
      array("country_iso" => "IO", "country_iso3" => "IOT", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "IQ", "country_iso3" => "IRQ", "code" => "IQD", "name" => "Iraq Dinar", "html_entity" => "&#1593;.&#1583;", "symbol" => "د.ع;"),
      array("country_iso" => "IR", "country_iso3" => "IRN", "code" => "IRR", "name" => "Iran Rial", "html_entity" => "&#65020;", "symbol" => "﷼"),
      array("country_iso" => "IS", "country_iso3" => "ISL", "code" => "ISK", "name" => "Iceland Krona", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "IT", "country_iso3" => "ITA", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "JE", "country_iso3" => "JEY", "code" => "GBP", "name" => "United Kingdom Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "JM", "country_iso3" => "JAM", "code" => "JMD", "name" => "Jamaica Dollar", "html_entity" => "&#74;&#36;", "symbol" => "J$"),
      array("country_iso" => "JO", "country_iso3" => "JOR", "code" => "JOD", "name" => "Jordan Dinar", "html_entity" => "&#74;&#68;", "symbol" => NULL),
      array("country_iso" => "JP", "country_iso3" => "JPN", "code" => "JPY", "name" => "Japan Yen", "html_entity" => "&#165;", "symbol" => "¥"),
      array("country_iso" => "KE", "country_iso3" => "KEN", "code" => "KES", "name" => "Kenya Shilling", "html_entity" => "&#x4B;&#x53;&#x68;", "symbol" => "KSh"),
      array("country_iso" => "KG", "country_iso3" => "KGZ", "code" => "KGS", "name" => "Kyrgyzstan Som", "html_entity" => "&#1083;&#1074;", "symbol" => "лв"),
      array("country_iso" => "KH", "country_iso3" => "KHM", "code" => "KHR", "name" => "Cambodia Riel", "html_entity" => "&#6107;", "symbol" => "៛"),
      array("country_iso" => "KI", "country_iso3" => "KIR", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "KM", "country_iso3" => "COM", "code" => "KMF", "name" => "Comoros Franc", "html_entity" => "&#67;&#70;", "symbol" => "Fr"),
      array("country_iso" => "KN", "country_iso3" => "KNA", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "KP", "country_iso3" => "PRK", "code" => "KPW", "name" => "Korea (North) Won", "html_entity" => "&#8361;", "symbol" => "₩"),
      array("country_iso" => "KR", "country_iso3" => "KOR", "code" => "KRW", "name" => "Korea (South) Won", "html_entity" => "&#8361;", "symbol" => "₩"),
      array("country_iso" => "KW", "country_iso3" => "KWT", "code" => "KWD", "name" => "Kuwait Dinar", "html_entity" => "&#1583;.&#1603;", "symbol" => "د.ك"),
      array("country_iso" => "KY", "country_iso3" => "CYM", "code" => "KYD", "name" => "Cayman Islands Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "KZ", "country_iso3" => "KAZ", "code" => "KZT", "name" => "Kazakhstan Tenge", "html_entity" => "&#1083;&#1074;", "symbol" => "лв"),
      array("country_iso" => "LA", "country_iso3" => "LAO", "code" => "LAK", "name" => "Laos Kip", "html_entity" => "&#8365;", "symbol" => "₭"),
      array("country_iso" => "LB", "country_iso3" => "LBN", "code" => "LBP", "name" => "Lebanon Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "LC", "country_iso3" => "LCA", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "LI", "country_iso3" => "LIE", "code" => "CHF", "name" => "Switzerland Franc", "html_entity" => "", "symbol" => "Fr"),
      array("country_iso" => "LK", "country_iso3" => "LKA", "code" => "LKR", "name" => "Sri Lanka Rupee", "html_entity" => "&#8360;", "symbol" => "₨"),
      array("country_iso" => "LR", "country_iso3" => "LBR", "code" => "LRD", "name" => "Liberia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "LS", "country_iso3" => "LSO", "code" => "LSL", "name" => "Lesotho Loti", "html_entity" => "&#76;", "symbol" => "M"),
      array("country_iso" => "LT", "country_iso3" => "LTU", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "LU", "country_iso3" => "LUX", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "LV", "country_iso3" => "LVA", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "LY", "country_iso3" => "LBY", "code" => "LYD", "name" => "Libya Dinar", "html_entity" => "&#1604;.&#1583;", "symbol" => "DL"),
      array("country_iso" => "MA", "country_iso3" => "MAR", "code" => "MAD", "name" => "Morocco Dirham", "html_entity" => "&#1583;.&#1605;.", "symbol" => "Dhs"),
      array("country_iso" => "MC", "country_iso3" => "MCO", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "MD", "country_iso3" => "MDA", "code" => "MDL", "name" => "Moldova Leu", "html_entity" => "&#76;", "symbol" => NULL),
      array("country_iso" => "ME", "country_iso3" => "MNE", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "MF", "country_iso3" => "MAF", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "MG", "country_iso3" => "MDG", "code" => "MGA", "name" => "Madagascar Ariary", "html_entity" => "&#65;&#114;", "symbol" => "Ar"),
      array("country_iso" => "MH", "country_iso3" => "MHL", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "MK", "country_iso3" => "MKD", "code" => "MKD", "name" => "Macedonia Denar", "html_entity" => "&#1076;&#1077;&#1085;", "symbol" => "ден"),
      array("country_iso" => "ML", "country_iso3" => "MLI", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "MM", "country_iso3" => "MMR", "code" => "MMK", "name" => "Myanmar (Burma) Kyat", "html_entity" => "&#75;", "symbol" => NULL),
      array("country_iso" => "MN", "country_iso3" => "MNG", "code" => "MNT", "name" => "Mongolia Tughrik", "html_entity" => "&#8366;", "symbol" => "₮"),
      array("country_iso" => "MO", "country_iso3" => "MAC", "code" => "MOP", "name" => "Macau Pataca", "html_entity" => "&#77;&#79;&#80;&#36;", "symbol" => NULL),
      array("country_iso" => "MP", "country_iso3" => "MNP", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "MQ", "country_iso3" => "MTQ", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "MR", "country_iso3" => "MRT", "code" => "MRO", "name" => "Mauritania Ouguiya", "html_entity" => "&#85;&#77;", "symbol" => "UM"),
      array("country_iso" => "MS", "country_iso3" => "MSR", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "MT", "country_iso3" => "MLT", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "MU", "country_iso3" => "MUS", "code" => "MUR", "name" => "Mauritius Rupee", "html_entity" => "&#8360;", "symbol" => "₨"),
      array("country_iso" => "MV", "country_iso3" => "MDV", "code" => "MVR", "name" => "Maldives (Maldive Islands) Rufiyaa", "html_entity" => ".&#1923;", "symbol" => NULL),
      array("country_iso" => "MW", "country_iso3" => "MWI", "code" => "MWK", "name" => "Malawi Kwacha", "html_entity" => "&#77;&#75;", "symbol" => "MK"),
      array("country_iso" => "MX", "country_iso3" => "MEX", "code" => "MXN", "name" => "Mexico Peso", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "MY", "country_iso3" => "MYS", "code" => "MYR", "name" => "Malaysia Ringgit", "html_entity" => "&#82;&#77;", "symbol" => "RM"),
      array("country_iso" => "MZ", "country_iso3" => "MOZ", "code" => "MZN", "name" => "Mozambique Metical", "html_entity" => "&#77;&#84;", "symbol" => "MT"),
      array("country_iso" => "NA", "country_iso3" => "NAM", "code" => "NAD", "name" => "Namibia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "NC", "country_iso3" => "NCL", "code" => "XPF", "name" => "Comptoirs Français du Pacifique (CFP) Franc", "html_entity" => "&#70;", "symbol" => "F"),
      array("country_iso" => "NE", "country_iso3" => "NER", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "NF", "country_iso3" => "NFK", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "NG", "country_iso3" => "NGA", "code" => "NGN", "name" => "Nigeria Naira", "html_entity" => "&#8358;", "symbol" => "₦"),
      array("country_iso" => "NI", "country_iso3" => "NIC", "code" => "NIO", "name" => "Nicaragua Cordoba", "html_entity" => "&#67;&#36;", "symbol" => "C$"),
      array("country_iso" => "NL", "country_iso3" => "NLD", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "NO", "country_iso3" => "NOR", "code" => "NOK", "name" => "Norway Krone", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "NP", "country_iso3" => "NPL", "code" => "NPR", "name" => "Nepal Rupee", "html_entity" => "&#8360;", "symbol" => "₨"),
      array("country_iso" => "NR", "country_iso3" => "NRU", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "NU", "country_iso3" => "NIU", "code" => "NZD", "name" => "New Zealand Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "NZ", "country_iso3" => "NZL", "code" => "NZD", "name" => "New Zealand Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "OM", "country_iso3" => "OMN", "code" => "OMR", "name" => "Oman Rial", "html_entity" => "&#65020;", "symbol" => "﷼"),
      array("country_iso" => "PA", "country_iso3" => "PAN", "code" => "PAB", "name" => "Panama Balboa", "html_entity" => "&#66;&#47;&#46;", "symbol" => "B/."),
      array("country_iso" => "PE", "country_iso3" => "PER", "code" => "PEN", "name" => "Peru Nuevo Sol", "html_entity" => "&#83;&#47;&#46;", "symbol" => "S/."),
      array("country_iso" => "PF", "country_iso3" => "PYF", "code" => "XPF", "name" => "Comptoirs Français du Pacifique (CFP) Franc", "html_entity" => "&#70;", "symbol" => "F"),
      array("country_iso" => "PG", "country_iso3" => "PNG", "code" => "PGK", "name" => "Papua New Guinea Kina", "html_entity" => "&#75;", "symbol" => NULL),
      array("country_iso" => "PH", "country_iso3" => "PHL", "code" => "PHP", "name" => "Philippines Peso", "html_entity" => "&#8369;", "symbol" => "₱"),
      array("country_iso" => "PK", "country_iso3" => "PAK", "code" => "PKR", "name" => "Pakistan Rupee", "html_entity" => "&#8360;", "symbol" => "₨"),
      array("country_iso" => "PL", "country_iso3" => "POL", "code" => "PLN", "name" => "Poland Zloty", "html_entity" => "&#122;&#322;", "symbol" => "zł"),
      array("country_iso" => "PM", "country_iso3" => "SPM", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "PN", "country_iso3" => "PCN", "code" => "NZD", "name" => "New Zealand Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "PR", "country_iso3" => "PRI", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "PS", "country_iso3" => "PSE", "code" => "ILS", "name" => "Israel Shekel", "html_entity" => "&#8362;", "symbol" => "₪"),
      array("country_iso" => "PT", "country_iso3" => "PRT", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "PW", "country_iso3" => "PLW", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "PY", "country_iso3" => "PRY", "code" => "PYG", "name" => "Paraguay Guarani", "html_entity" => "&#71;&#115;", "symbol" => "Gs"),
      array("country_iso" => "QA", "country_iso3" => "QAT", "code" => "QAR", "name" => "Qatar Riyal", "html_entity" => "&#65020;", "symbol" => "﷼"),
      array("country_iso" => "RE", "country_iso3" => "REU", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "RO", "country_iso3" => "ROU", "code" => "RON", "name" => "Romania New Leu", "html_entity" => "&#108;&#101;&#105;", "symbol" => "lei"),
      array("country_iso" => "RS", "country_iso3" => "SRB", "code" => "RSD", "name" => "Serbia Dinar", "html_entity" => "&#1044;&#1080;&#1085;&#46;", "symbol" => "Дин."),
      array("country_iso" => "RU", "country_iso3" => "RUS", "code" => "RUB", "name" => "Russia Ruble", "html_entity" => "&#1088;&#1091;&#1073;", "symbol" => "руб"),
      array("country_iso" => "RW", "country_iso3" => "RWA", "code" => "RWF", "name" => "Rwanda Franc", "html_entity" => "&#1585;.&#1587;", "symbol" => "FRw"),
      array("country_iso" => "SA", "country_iso3" => "SAU", "code" => "SAR", "name" => "Saudi Arabia Riyal", "html_entity" => "&#65020;", "symbol" => "﷼"),
      array("country_iso" => "SB", "country_iso3" => "SLB", "code" => "SBD", "name" => "Solomon Islands Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "SC", "country_iso3" => "SYC", "code" => "SCR", "name" => "Seychelles Rupee", "html_entity" => "&#8360;", "symbol" => "₨"),
      array("country_iso" => "SD", "country_iso3" => "SDN", "code" => "SDG", "name" => "Sudan Pound", "html_entity" => "&#163;", "symbol" => "DS"),
      array("country_iso" => "SE", "country_iso3" => "SWE", "code" => "SEK", "name" => "Sweden Krona", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "SG", "country_iso3" => "SGP", "code" => "SGD", "name" => "Singapore Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "SH", "country_iso3" => "SHN", "code" => "SHP", "name" => "Saint Helena Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "SI", "country_iso3" => "SVN", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "SJ", "country_iso3" => "SJM", "code" => "NOK", "name" => "Norway Krone", "html_entity" => "&#107;&#114;", "symbol" => "kr"),
      array("country_iso" => "SK", "country_iso3" => "SVK", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "SL", "country_iso3" => "SLE", "code" => "SLL", "name" => "Sierra Leone Leone", "html_entity" => "&#76;&#101;", "symbol" => "Le"),
      array("country_iso" => "SM", "country_iso3" => "SMR", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "SN", "country_iso3" => "SEN", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "SO", "country_iso3" => "SOM", "code" => "SOS", "name" => "Somalia Shilling", "html_entity" => "&#83;", "symbol" => "S"),
      array("country_iso" => "SR", "country_iso3" => "SUR", "code" => "SRD", "name" => "Suriname Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "SS", "country_iso3" => "SSD", "code" => "SSP", "name" => "South Sudanese Pound", "html_entity" => "&#xA3;", "symbol" => "£"),
      array("country_iso" => "ST", "country_iso3" => "STP", "code" => "STD", "name" => "São Tomé and Príncipe Dobra", "html_entity" => "&#68;&#98;", "symbol" => "Db"),
      array("country_iso" => "SV", "country_iso3" => "SLV", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "SX", "country_iso3" => "SXM", "code" => "ANG", "name" => "Netherlands Antilles Guilder", "html_entity" => "&#402;", "symbol" => "ƒ"),
      array("country_iso" => "SY", "country_iso3" => "SYR", "code" => "SYP", "name" => "Syria Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "SZ", "country_iso3" => "SWZ", "code" => "SZL", "name" => "Swaziland Lilangeni", "html_entity" => "&#76;", "symbol" => "E"),
      array("country_iso" => "TC", "country_iso3" => "TCA", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "TD", "country_iso3" => "TCD", "code" => "XAF", "name" => "Communauté Financière Africaine (BEAC) CFA Franc B", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "TF", "country_iso3" => "ATF", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "TG", "country_iso3" => "TGO", "code" => "XOF", "name" => "Communauté Financière Africaine (BCEAO) Franc", "html_entity" => "&#70;&#67;&#70;&#65;", "symbol" => "F"),
      array("country_iso" => "TH", "country_iso3" => "THA", "code" => "THB", "name" => "Thailand Baht", "html_entity" => "&#3647;", "symbol" => "฿"),
      array("country_iso" => "TJ", "country_iso3" => "TJK", "code" => "TJS", "name" => "Tajikistan Somoni", "html_entity" => "&#84;&#74;&#83;", "symbol" => NULL),
      array("country_iso" => "TK", "country_iso3" => "TKL", "code" => "NZD", "name" => "New Zealand Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "TL", "country_iso3" => "TLS", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "TM", "country_iso3" => "TKM", "code" => "TMT", "name" => "Turkmenistan Manat", "html_entity" => "&#109;", "symbol" => NULL),
      array("country_iso" => "TN", "country_iso3" => "TUN", "code" => "TND", "name" => "Tunisia Dinar", "html_entity" => "&#1583;.&#1578;", "symbol" => "DT"),
      array("country_iso" => "TO", "country_iso3" => "TON", "code" => "TOP", "name" => "Tonga Pa'anga", "html_entity" => "&#84;&#36;", "symbol" => NULL),
      array("country_iso" => "TR", "country_iso3" => "TUR", "code" => "TRY", "name" => "Turkey Lira", "html_entity" => "&#x20BA;", "symbol" => "₺"),
      array("country_iso" => "TT", "country_iso3" => "TTO", "code" => "TTD", "name" => "Trinidad and Tobago Dollar", "html_entity" => "&#36;", "symbol" => "TT$"),
      array("country_iso" => "TV", "country_iso3" => "TUV", "code" => "AUD", "name" => "Australia Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "TW", "country_iso3" => "TWN", "code" => "TWD", "name" => "Taiwan New Dollar", "html_entity" => "&#78;&#84;&#36;", "symbol" => "NT$"),
      array("country_iso" => "TZ", "country_iso3" => "TZA", "code" => "TZS", "name" => "Tanzania Shilling", "html_entity" => "&#x54;&#x53;&#x68;", "symbol" => "TSh"),
      array("country_iso" => "UA", "country_iso3" => "UKR", "code" => "UAH", "name" => "Ukraine Hryvnia", "html_entity" => "&#8372;", "symbol" => "₴"),
      array("country_iso" => "UG", "country_iso3" => "UGA", "code" => "UGX", "name" => "Uganda Shilling", "html_entity" => "&#85;&#83;&#104;", "symbol" => "USh"),
      array("country_iso" => "UK", "country_iso3" => "GBR", "code" => "GBP", "name" => "United Kingdom Pound", "html_entity" => "&#163;", "symbol" => "£"),
      array("country_iso" => "UM", "country_iso3" => "UMI", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "US", "country_iso3" => "USA", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "UY", "country_iso3" => "URY", "code" => "UYU", "name" => "Uruguay Peso", "html_entity" => "&#36;&#85;", "symbol" => '$U'),
      array("country_iso" => "UZ", "country_iso3" => "UZB", "code" => "UZS", "name" => "Uzbekistan Som", "html_entity" => "&#1083;&#1074;", "symbol" => "лв"),
      array("country_iso" => "VA", "country_iso3" => "VAT", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "VC", "country_iso3" => "VCT", "code" => "XCD", "name" => "East Caribbean Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "VE", "country_iso3" => "VEN", "code" => "VEF", "name" => "Venezuela Bolivar", "html_entity" => "&#66;&#115;", "symbol" => "Bs"),
      array("country_iso" => "VG", "country_iso3" => "VGB", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "VI", "country_iso3" => "VIR", "code" => "USD", "name" => "United States Dollar", "html_entity" => "&#36;", "symbol" => "$"),
      array("country_iso" => "VN", "country_iso3" => "VNM", "code" => "VND", "name" => "Viet Nam Dong", "html_entity" => "&#8363;", "symbol" => "₫"),
      array("country_iso" => "VU", "country_iso3" => "VUT", "code" => "VUV", "name" => "Vanuatu Vatu", "html_entity" => "&#86;&#84;", "symbol" => NULL),
      array("country_iso" => "WF", "country_iso3" => "WLF", "code" => "XPF", "name" => "Comptoirs Français du Pacifique (CFP) Franc", "html_entity" => "&#70;", "symbol" => "F"),
      array("country_iso" => "WS", "country_iso3" => "WSM", "code" => "WST", "name" => "Samoa Tala", "html_entity" => "&#87;&#83;&#36;", "symbol" => NULL),
      array("country_iso" => "XK", "country_iso3" => "XKX", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "YE", "country_iso3" => "YEM", "code" => "YER", "name" => "Yemen Rial", "html_entity" => "&#65020;", "symbol" => "﷼"),
      array("country_iso" => "YT", "country_iso3" => "MYT", "code" => "EUR", "name" => "Euro Member Countries", "html_entity" => "€", "symbol" => "€"),
      array("country_iso" => "ZA", "country_iso3" => "ZAF", "code" => "ZAR", "name" => "South Africa Rand", "html_entity" => "&#82;", "symbol" => "R"),
      array("country_iso" => "ZM", "country_iso3" => "ZMB", "code" => "ZMW", "name" => "Zambia Kwacha", "html_entity" => NULL, "symbol" => "ZK"),
      array("country_iso" => "ZW", "country_iso3" => "ZWE", "code" => "ZWL", "name" => "Zimbabwe Dollar", "html_entity" => NULL, "symbol" => "Z$")
    );
    $currencyProgressBar = $this->command->getOutput()->createProgressBar(count($currencies));
    foreach ($currencies as $currency) {
      Currency::create($currency);
      $currencyProgressBar->advance();
    }
    $currencyProgressBar->finish();
  }
}
